// ---------- Rock & mineral knowledge base ----------
// Curated trait data for the identification engine and field guide.
// Hardness is the Mohs center value; luster/colors/habit use the
// canonical vocab from types.ts so scoring works.

import type { RockGroup, RockSpec } from "./types";

export const ROCKS: RockSpec[] = [
  // ============ IGNEOUS ============
  {
    id: "granite", name: "Granite", group: "igneous", mohs: 6.5,
    luster: ["vitreous", "earthy"], colors: ["white", "gray", "pink", "black"],
    habit: ["granular"], gravity: "medium",
    looks: "Coarse-grained speckled rock — visible quartz, feldspar and mica.",
    hints: "Salt-and-pepper speckle you can see with the naked eye.",
    uses: "Countertops, monuments, buildings", emoji: "🏔️",
  },
  {
    id: "pegmatite", name: "Pegmatite", group: "igneous", mohs: 6.5,
    luster: ["vitreous"], colors: ["white", "gray", "pink"],
    habit: ["granular", "crystals"], gravity: "medium",
    looks: "Granite with giant crystals — some bigger than your thumb.",
    hints: "Crystal grains larger than ~1 cm = pegmatite.", emoji: "💎",
  },
  {
    id: "basalt", name: "Basalt", group: "igneous", mohs: 6,
    luster: ["earthy"], colors: ["black", "gray"],
    habit: ["massive"], gravity: "medium",
    looks: "Dense, fine-grained dark gray to black volcanic rock.",
    hints: "Dark, dense and fine-grained — the most common volcanic rock.",
    uses: "Road base, sea-cliff columns", emoji: "🌋",
  },
  {
    id: "gabbro", name: "Gabbro", group: "igneous", mohs: 6.5,
    luster: ["earthy", "vitreous"], colors: ["black", "gray", "green"],
    habit: ["granular"], gravity: "heavy",
    looks: "Coarse-grained dark rock — the intrusive twin of basalt.",
    hints: "Dark speckled coarse rock, heavier than basalt.", emoji: "🪨",
  },
  {
    id: "diorite", name: "Diorite", group: "igneous", mohs: 6.5,
    luster: ["earthy"], colors: ["gray", "white", "black"],
    habit: ["granular"], gravity: "medium",
    looks: "Salt-and-pepper rock with less quartz than granite.",
    hints: "Speckled gray — halfway between granite and gabbro.", emoji: "🪨",
  },
  {
    id: "obsidian", name: "Obsidian", group: "igneous", mohs: 5.5,
    luster: ["vitreous"], colors: ["black", "brown", "green"],
    habit: ["glassy"], gravity: "medium",
    looks: "Natural volcanic glass — smooth with shell-like (conchoidal) fractures.",
    hints: "Breaks like glass with curved fracture surfaces.",
    uses: "Arrowheads, scalpels, jewelry", emoji: "🖤",
  },
  {
    id: "pumice", name: "Pumice", group: "igneous", mohs: 6,
    luster: ["earthy"], colors: ["white", "gray", "tan"],
    habit: ["porous"], gravity: "light",
    looks: "Very light, frothy volcanic rock full of gas bubbles.",
    hints: "Floats on water — that's the giveaway.",
    uses: "Pumice stone, exfoliant", emoji: "🫧",
  },
  {
    id: "scoria", name: "Scoria", group: "igneous", mohs: 5.5,
    luster: ["earthy"], colors: ["red", "brown", "black"],
    habit: ["porous"], gravity: "medium",
    looks: "Dark, bubbly volcanic rock — heavier than pumice.",
    hints: "Bubbly dark rock that sinks; often reddish.",
    uses: "Landscaping, BBQ rocks", emoji: "🟤",
  },
  {
    id: "rhyolite", name: "Rhyolite", group: "igneous", mohs: 6.5,
    luster: ["earthy", "vitreous"], colors: ["pink", "gray", "tan"],
    habit: ["massive", "banded"], gravity: "medium",
    looks: "Light-colored, fine-grained volcanic rock, sometimes banded.",
    hints: "Light color + fine grain — the lava version of granite.", emoji: "🩷",
  },
  {
    id: "andesite", name: "Andesite", group: "igneous", mohs: 6,
    luster: ["earthy"], colors: ["gray"],
    habit: ["massive"], gravity: "medium",
    looks: "Medium gray, fine-grained volcanic rock.",
    hints: "Gray and fine-grained — common in mountain volcanoes.", emoji: "🏔️",
  },
  {
    id: "tuff", name: "Tuff", group: "igneous", mohs: 3.5,
    luster: ["earthy"], colors: ["gray", "tan"],
    habit: ["porous", "layered"], gravity: "light",
    looks: "Compacted volcanic ash — light, crumbly, may hold pumice bits.",
    hints: "Feels like hardened ash; light for its size.", emoji: "🌫️",
  },

  // ============ SEDIMENTARY ============
  {
    id: "sandstone", name: "Sandstone", group: "sedimentary", mohs: 6,
    luster: ["earthy"], colors: ["tan", "brown", "red", "gray"],
    habit: ["granular"], gravity: "medium",
    looks: "Sand-sized grains cemented together — gritty to the touch.",
    hints: "Rub it: grains of sand come off.",
    uses: "Building stone, paving", emoji: "🏜️",
  },
  {
    id: "conglomerate", name: "Conglomerate", group: "sedimentary", mohs: 6,
    luster: ["earthy"], colors: ["gray", "tan"],
    habit: ["granular"], gravity: "medium",
    looks: "Rounded pebbles cemented in a finer sandy matrix.",
    hints: "A rock full of rounded river pebbles.", emoji: "🔮",
  },
  {
    id: "breccia", name: "Breccia", group: "sedimentary", mohs: 6,
    luster: ["earthy"], colors: ["gray", "tan", "red"],
    habit: ["granular"], gravity: "medium",
    looks: "Sharp, angular rock fragments cemented together.",
    hints: "Angular broken pieces — unlike conglomerate's rounded ones.", emoji: "🔺",
  },
  {
    id: "limestone", name: "Limestone", group: "sedimentary", mohs: 3.5,
    luster: ["earthy"], colors: ["gray", "tan", "white"],
    habit: ["massive"], gravity: "medium", reactsToAcid: true,
    looks: "Smooth, fine-grained rock that fizzes with vinegar; often holds fossils.",
    hints: "Drops of vinegar bubble. Frequently contains fossil shells.",
    uses: "Cement, lime, building stone", emoji: "🐚",
  },
  {
    id: "dolomite", name: "Dolomite", group: "sedimentary", mohs: 4,
    luster: ["earthy", "pearly"], colors: ["tan", "pink", "white"],
    habit: ["massive"], gravity: "medium", reactsToAcid: true,
    looks: "Tan or pink rock that looks like limestone.",
    hints: "Fizzes only weakly — try scratching the surface first.", emoji: "🌸",
  },
  {
    id: "chalk", name: "Chalk", group: "sedimentary", mohs: 1.5,
    luster: ["earthy"], colors: ["white"],
    habit: ["chalky"], gravity: "light",
    looks: "Soft white powdery rock that writes on surfaces.",
    hints: "Leaves white dust on your fingers.", emoji: "🤍",
  },
  {
    id: "travertine", name: "Travertine", group: "sedimentary", mohs: 3.5,
    luster: ["earthy"], colors: ["tan", "white", "tan"],
    habit: ["banded", "porous"], gravity: "medium",
    looks: "Layered cream/tan rock deposited by hot springs.",
    hints: "Wavy bands and small holes from mineral springs.",
    uses: "Tiles, decorative stone", emoji: "🏛️",
  },
  {
    id: "shale", name: "Shale", group: "sedimentary", mohs: 3,
    luster: ["earthy"], colors: ["gray", "black", "brown", "red"],
    habit: ["layered"], gravity: "medium",
    looks: "Thin layers of mud that split into sheets.",
    hints: "Splits into flat sheets along its layers.", emoji: "📚",
  },
  {
    id: "siltstone", name: "Siltstone", group: "sedimentary", mohs: 4,
    luster: ["earthy"], colors: ["gray", "tan"],
    habit: ["massive"], gravity: "medium",
    looks: "Finer than sandstone; feels slightly gritty between teeth/fingers.",
    hints: "Between mudstone and sandstone in grain size.", emoji: "🟫",
  },
  {
    id: "mudstone", name: "Mudstone", group: "sedimentary", mohs: 3.5,
    luster: ["earthy"], colors: ["gray", "brown"],
    habit: ["massive"], gravity: "medium",
    looks: "Smooth, dull rock with no visible layers and no grit.",
    hints: "Smooth, blocky breaks, no layering.", emoji: "🟤",
  },
  {
    id: "coal", name: "Coal", group: "sedimentary", mohs: 2,
    luster: ["earthy", "vitreous"], colors: ["black"],
    habit: ["massive"], gravity: "light",
    looks: "Soft black rock that smudges your fingers.",
    hints: "Black, light, smudges — sometimes woody texture.",
    uses: "Fuel (historic)", emoji: "⬛",
  },
  {
    id: "chert", name: "Chert / Flint", group: "sedimentary", mohs: 7,
    luster: ["waxy", "earthy"], colors: ["gray", "brown", "black", "red"],
    habit: ["massive"], gravity: "medium",
    looks: "Hard, smooth rock that breaks with conchoidal fractures.",
    hints: "Harder than glass; sparks when struck against steel.",
    uses: "Arrowheads, fire starting", emoji: "🔥",
  },
  {
    id: "ironstone", name: "Ironstone", group: "sedimentary", mohs: 5.5,
    luster: ["earthy"], colors: ["brown", "red"],
    habit: ["massive"], gravity: "heavy",
    looks: "Heavy brown/red rock with a rusty look.",
    hints: "Rusty brown and heavier than it looks — iron-rich.", emoji: "🦀",
  },

  // ============ METAMORPHIC ============
  {
    id: "slate", name: "Slate", group: "metamorphic", mohs: 3.5,
    luster: ["earthy"], colors: ["gray", "black", "green", "purple"],
    habit: ["layered"], gravity: "medium",
    looks: "Fine-grained rock that splits into smooth, flat sheets.",
    hints: "Splits into flat sheets, smoother than shale.",
    uses: "Roofing, chalkboards", emoji: "🏠",
  },
  {
    id: "phyllite", name: "Phyllite", group: "metamorphic", mohs: 3,
    luster: ["silky", "earthy"], colors: ["gray", "green", "silver"],
    habit: ["layered"], gravity: "medium",
    looks: "Wrinkly, wavy layers with a silky sheen.",
    hints: "Shiny wavy surface — between slate and schist.", emoji: "✨",
  },
  {
    id: "schist", name: "Schist", group: "metamorphic", mohs: 4.5,
    luster: ["silky", "vitreous"], colors: ["silver", "gray", "green", "brown"],
    habit: ["layered"], gravity: "medium",
    looks: "Sparkly rock with visible mica flakes and wavy layers.",
    hints: "Glittery mica flakes you can see with the eye.", emoji: "🌟",
  },
  {
    id: "gneiss", name: "Gneiss", group: "metamorphic", mohs: 6.5,
    luster: ["earthy", "vitreous"], colors: ["gray", "pink", "white"],
    habit: ["banded"], gravity: "medium",
    looks: "Coarse rock with alternating light and dark bands.",
    hints: "Striped bands of light and dark minerals.", emoji: "🦓",
  },
  {
    id: "marble", name: "Marble", group: "metamorphic", mohs: 3.5,
    luster: ["vitreous", "pearly"], colors: ["white", "pink", "gray", "green"],
    habit: ["massive"], gravity: "medium", reactsToAcid: true,
    looks: "Smooth rock with a sugary sparkle that fizzes with vinegar.",
    hints: "Fizzes with acid + sugary crystalline texture.",
    uses: "Sculpture, buildings, tiles", emoji: "🗿",
  },
  {
    id: "quartzite", name: "Quartzite", group: "metamorphic", mohs: 7,
    luster: ["vitreous"], colors: ["white", "gray", "pink", "red"],
    habit: ["massive"], gravity: "medium",
    looks: "Very hard rock — breaks through grains, not around them.",
    hints: "Scratches glass; breaks across grains; glassy luster.", emoji: "🔆",
  },
  {
    id: "hornfels", name: "Hornfels", group: "metamorphic", mohs: 5.5,
    luster: ["earthy"], colors: ["gray", "black"],
    habit: ["massive"], gravity: "medium",
    looks: "Hard, dull, dark rock baked next to hot intrusions.",
    hints: "Dull, hard, dark — found near igneous bodies.", emoji: "⬛",
  },
  {
    id: "soapstone", name: "Soapstone", group: "metamorphic", mohs: 1.5,
    luster: ["greasy", "waxy"], colors: ["gray", "green"],
    habit: ["massive"], gravity: "medium",
    looks: "Feels soapy; a fingernail easily scratches it.",
    hints: "Soapy feel = soapstone.",
    uses: "Carving, countertops", emoji: "🧼",
  },
  {
    id: "serpentine", name: "Serpentine", group: "metamorphic", mohs: 4,
    luster: ["waxy", "greasy"], colors: ["green"],
    habit: ["massive"], gravity: "medium",
    looks: "Green, waxy rock, sometimes mottled like snake skin.",
    hints: "Green + waxy + slippery feel.", emoji: "🐍",
  },
  {
    id: "anthracite", name: "Anthracite", group: "metamorphic", mohs: 2.5,
    luster: ["vitreous"], colors: ["black"],
    habit: ["massive"], gravity: "medium",
    looks: "Shiny black, hard coal with a conchoidal fracture.",
    hints: "Very shiny black, breaks with curved surfaces.", emoji: "🖤",
  },
  {
    id: "amphibolite", name: "Amphibolite", group: "metamorphic", mohs: 6,
    luster: ["earthy"], colors: ["green", "black"],
    habit: ["granular"], gravity: "medium",
    looks: "Dark rock of black/green amphibole with light streaks.",
    hints: "Dark, coarse, greenish-black with white feldspar.", emoji: "🟩",
  },

  // ============ MINERALS ============
  {
    id: "quartz", name: "Quartz", group: "mineral", mohs: 7,
    luster: ["vitreous"], colors: ["clear", "white", "gray", "pink", "purple"],
    habit: ["crystals"], streak: "white", gravity: "medium",
    looks: "Six-sided pointed crystals, glassy and hard.",
    hints: "Scratches glass; glassy luster; clear or milky.", emoji: "🔷",
  },
  {
    id: "amethyst", name: "Amethyst", group: "mineral", mohs: 7,
    luster: ["vitreous"], colors: ["purple"],
    habit: ["crystals"], streak: "white", gravity: "medium",
    looks: "Purple quartz crystals — the violet variety of quartz.",
    hints: "Purple = amethyst.", emoji: "💜",
  },
  {
    id: "citrine", name: "Citrine", group: "mineral", mohs: 7,
    luster: ["vitreous"], colors: ["yellow", "orange"],
    habit: ["crystals"], streak: "white", gravity: "medium",
    looks: "Yellow-to-orange quartz.",
    hints: "Golden/yellow quartz variety.", emoji: "🟡",
  },
  {
    id: "rosequartz", name: "Rose Quartz", group: "mineral", mohs: 7,
    luster: ["vitreous"], colors: ["pink"],
    habit: ["massive"], streak: "white", gravity: "medium",
    looks: "Pink, cloudy quartz without crystal faces.",
    hints: "Milky pink, usually not crystal-shaped.", emoji: "🌸",
  },
  {
    id: "agate", name: "Agate", group: "mineral", mohs: 7,
    luster: ["waxy"], colors: ["red", "brown", "gray", "blue", "white", "pink"],
    habit: ["banded"], streak: "white", gravity: "medium",
    looks: "Banded, waxy microcrystalline quartz.",
    hints: "Waxy luster + colorful concentric bands.", emoji: "🎯",
  },
  {
    id: "jasper", name: "Jasper", group: "mineral", mohs: 7,
    luster: ["earthy", "waxy"], colors: ["red", "brown", "yellow", "green"],
    habit: ["massive"], streak: "white", gravity: "medium",
    looks: "Opaque, dull red or brown quartz rock.",
    hints: "Opaque and earthy, often brick red.", emoji: "🔴",
  },
  {
    id: "calcite", name: "Calcite", group: "mineral", mohs: 3,
    luster: ["vitreous", "pearly"], colors: ["white", "clear", "yellow", "pink"],
    habit: ["crystals"], streak: "white", gravity: "medium", reactsToAcid: true,
    looks: "Soft clear/white crystals that fizz with vinegar.",
    hints: "Fizzes with vinegar; a coin scratches it; perfect rhombohedral cleavage.",
    uses: "Lime, cement, optical instruments", emoji: "🧊",
  },
  {
    id: "feldspar", name: "Feldspar", group: "mineral", mohs: 6,
    luster: ["vitreous"], colors: ["pink", "white", "gray"],
    habit: ["crystals"], streak: "white", gravity: "medium",
    looks: "Pink or white blocky crystals — the most common mineral in crust.",
    hints: "Pink/white, blocky, two good cleavages; big part of granite.", emoji: "🩷",
  },
  {
    id: "muscovite", name: "Muscovite (White Mica)", group: "mineral", mohs: 2.5,
    luster: ["pearly"], colors: ["silver", "clear", "gold"],
    habit: ["layered"], streak: "white", gravity: "light",
    looks: "Peels into thin, flexible, shiny sheets.",
    hints: "Thin elastic sheets that sparkle.", emoji: "🎞️",
  },
  {
    id: "biotite", name: "Biotite (Black Mica)", group: "mineral", mohs: 2.5,
    luster: ["vitreous", "pearly"], colors: ["black", "brown"],
    habit: ["layered"], streak: "white", gravity: "light",
    looks: "Black mica that peels into thin sheets.",
    hints: "Black version of mica.", emoji: "🖤",
  },
  {
    id: "pyrite", name: "Pyrite (Fool's Gold)", group: "mineral", mohs: 6.5,
    luster: ["metallic"], colors: ["gold"],
    habit: ["crystals"], streak: "greenish-black", gravity: "heavy",
    looks: "Golden cubic crystals — fool's gold.",
    hints: "Cubes, gold color, but streaks greenish-black and is brittle.", emoji: "🟨",
  },
  {
    id: "hematite", name: "Hematite", group: "mineral", mohs: 6,
    luster: ["metallic", "earthy"], colors: ["gray", "red", "black"],
    habit: ["massive"], streak: "red-brown", gravity: "heavy",
    looks: "Heavy gray or rust-red rock.",
    hints: "Red-brown streak on tile; heavy; often metallic gray.", emoji: "🔴",
  },
  {
    id: "magnetite", name: "Magnetite", group: "mineral", mohs: 6,
    luster: ["metallic"], colors: ["black"],
    habit: ["massive"], streak: "black", gravity: "heavy", magnetic: true,
    looks: "Black, heavy rock that sticks to a magnet.",
    hints: "Strongly magnetic — the test is instant.", emoji: "🧲",
  },
  {
    id: "galena", name: "Galena", group: "mineral", mohs: 2.5,
    luster: ["metallic"], colors: ["silver"],
    habit: ["crystals"], streak: "gray", gravity: "heavy",
    looks: "Heavy silver cubic crystals — lead ore.",
    hints: "Very heavy; cubic cleavage; silver metallic.", emoji: "🥈",
  },
  {
    id: "chalcopyrite", name: "Chalcopyrite", group: "mineral", mohs: 4,
    luster: ["metallic"], colors: ["gold", "yellow"],
    habit: ["massive"], streak: "greenish-black", gravity: "heavy",
    looks: "Brassy yellow metallic mineral.",
    hints: "Tarnishes to peacock iridescence; softer than pyrite.", emoji: "🦚",
  },
  {
    id: "bornite", name: "Bornite (Peacock Ore)", group: "mineral", mohs: 3,
    luster: ["metallic"], colors: ["brown", "purple", "blue"],
    habit: ["massive"], streak: "gray-black", gravity: "heavy",
    looks: "Brown mineral that tarnishes to peacock purple/blue.",
    hints: "The iridescent purple-blue tarnish is unmistakable.", emoji: "🦚",
  },
  {
    id: "malachite", name: "Malachite", group: "mineral", mohs: 4,
    luster: ["silky", "earthy"], colors: ["green"],
    habit: ["banded", "massive"], streak: "light green", gravity: "medium",
    looks: "Bright green banded mineral.",
    hints: "Vivid green with bands; often near azurite.", emoji: "🟢",
  },
  {
    id: "azurite", name: "Azurite", group: "mineral", mohs: 4,
    luster: ["vitreous"], colors: ["blue"],
    habit: ["crystals", "massive"], streak: "light blue", gravity: "medium",
    looks: "Deep blue mineral, often in clusters.",
    hints: "Vivid blue; found with malachite.", emoji: "🔵",
  },
  {
    id: "fluorite", name: "Fluorite", group: "mineral", mohs: 4,
    luster: ["vitreous"], colors: ["purple", "green", "blue", "yellow"],
    habit: ["crystals"], streak: "white", gravity: "medium",
    looks: "Cubic crystals in many colors; glows under UV.",
    hints: "Cubes, many colors, soft (knife scratches it).", emoji: "🌈",
  },
  {
    id: "gypsum", name: "Gypsum", group: "mineral", mohs: 2,
    luster: ["vitreous", "pearly"], colors: ["white", "clear", "pink"],
    habit: ["crystals", "fibrous"], streak: "white", gravity: "light",
    looks: "Very soft white/clear crystals — a fingernail scratches them.",
    hints: "Fingernail scratches it; clear sheets are selenite.",
    uses: "Drywall, plaster, alabaster", emoji: "🤍",
  },
  {
    id: "halite", name: "Halite (Rock Salt)", group: "mineral", mohs: 2.5,
    luster: ["vitreous"], colors: ["clear", "white", "pink"],
    habit: ["crystals"], streak: "white", gravity: "light",
    looks: "Rock salt — cube-shaped crystals that taste salty.",
    hints: "Cube cleavage + salty taste (lick a corner).", emoji: "🧂",
  },
  {
    id: "talc", name: "Talc", group: "mineral", mohs: 1,
    luster: ["pearly", "greasy"], colors: ["white", "green", "gray"],
    habit: ["massive"], streak: "white", gravity: "light",
    looks: "The softest mineral — feels soapy, scratches with a fingernail.",
    hints: "Easily scratched, soapy, greasy feel.",
    uses: "Talcum powder, ceramics", emoji: "🧴",
  },
  {
    id: "olivine", name: "Olivine", group: "mineral", mohs: 7,
    luster: ["vitreous"], colors: ["green"],
    habit: ["granular"], streak: "white", gravity: "medium",
    looks: "Olive-green glassy grains inside dark rocks.",
    hints: "Green glassy grains in basalt-like rock.", emoji: "🫒",
  },
  {
    id: "garnet", name: "Garnet", group: "mineral", mohs: 7,
    luster: ["vitreous"], colors: ["red", "brown"],
    habit: ["crystals"], streak: "white", gravity: "medium",
    looks: "Dark red rounded crystal grains (12-sided).",
    hints: "Dark red, rounded crystal faces; common in schist.", emoji: "🔺",
  },
  {
    id: "tourmaline", name: "Tourmaline", group: "mineral", mohs: 7.5,
    luster: ["vitreous"], colors: ["black", "pink", "green"],
    habit: ["crystals"], streak: "white", gravity: "medium",
    looks: "Long, ridged prism crystals with rounded triangle cross-section.",
    hints: "Long prisms, triangular cross-section.", emoji: "🖋️",
  },
  {
    id: "topaz", name: "Topaz", group: "mineral", mohs: 8,
    luster: ["vitreous"], colors: ["yellow", "blue", "clear"],
    habit: ["crystals"], streak: "white", gravity: "medium",
    looks: "Hard yellow/blue/clear prismatic crystals.",
    hints: "Very hard; often sherry-yellow.", emoji: "🟡",
  },
  {
    id: "corundum", name: "Corundum (Ruby/Sapphire)", group: "mineral", mohs: 9,
    luster: ["adamantine", "vitreous"], colors: ["gray", "blue", "red"],
    habit: ["crystals"], streak: "white", gravity: "heavy",
    looks: "Very hard barrel-shaped crystals — ruby and sapphire.",
    hints: "Second-hardest common mineral; scratches almost everything.", emoji: "💙",
  },
  {
    id: "diamond", name: "Diamond", group: "mineral", mohs: 10,
    luster: ["adamantine"], colors: ["clear", "yellow", "brown"],
    habit: ["crystals"], gravity: "medium",
    looks: "The hardest mineral — brilliant sparkle, octahedral crystals.",
    hints: "Scratches everything; greasy-shiny sparkle.", emoji: "💎",
  },
  {
    id: "kyanite", name: "Kyanite", group: "mineral", mohs: 5,
    luster: ["vitreous"], colors: ["blue"],
    habit: ["crystals"], streak: "white", gravity: "medium",
    looks: "Blade-like blue crystals with unusual variable hardness.",
    hints: "Blue blades; hardness differs along vs across the blade.", emoji: "🔷",
  },
  {
    id: "staurolite", name: "Staurolite (Fairy Cross)", group: "mineral", mohs: 7,
    luster: ["vitreous", "earthy"], colors: ["brown"],
    habit: ["crystals"], streak: "white", gravity: "medium",
    looks: "Brown cross-shaped twinned crystals.",
    hints: "Fairy crosses — brown X or + shapes.", emoji: "✝️",
  },
  {
    id: "epidote", name: "Epidote", group: "mineral", mohs: 6.5,
    luster: ["vitreous"], colors: ["green"],
    habit: ["crystals"], streak: "white", gravity: "medium",
    looks: "Pistachio-green prismatic crystals.",
    hints: "Distinctive green — pistachio color.", emoji: "🟩",
  },
  {
    id: "apatite", name: "Apatite", group: "mineral", mohs: 5,
    luster: ["vitreous"], colors: ["green", "blue"],
    habit: ["crystals"], streak: "white", gravity: "medium",
    looks: "Hexagonal green or blue crystals.",
    hints: "Six-sided prisms; softer than beryl.", emoji: "🟢",
  },
  {
    id: "beryl", name: "Beryl (Emerald/Aquamarine)", group: "mineral", mohs: 8,
    luster: ["vitreous"], colors: ["green", "blue", "clear"],
    habit: ["crystals"], streak: "white", gravity: "medium",
    looks: "Hexagonal green (emerald) or blue (aquamarine) crystals.",
    hints: "Hard hexagonal prisms.", emoji: "💚",
  },
  {
    id: "sodalite", name: "Sodalite", group: "mineral", mohs: 6,
    luster: ["vitreous"], colors: ["blue"],
    habit: ["massive"], streak: "white", gravity: "medium",
    looks: "Deep blue stone with white veins.",
    hints: "Blue with white calcite veining.", emoji: "🔵",
  },
  {
    id: "lapislazuli", name: "Lapis Lazuli", group: "mineral", mohs: 5.5,
    luster: ["earthy"], colors: ["blue"],
    habit: ["massive"], streak: "light blue", gravity: "medium",
    looks: "Deep blue stone flecked with gold pyrite.",
    hints: "Royal blue + gold sparkles.", emoji: "💙",
  },
  {
    id: "turquoise", name: "Turquoise", group: "mineral", mohs: 5.5,
    luster: ["waxy"], colors: ["blue", "green"],
    habit: ["massive"], streak: "white", gravity: "medium",
    looks: "Opaque blue-green waxy stone.",
    hints: "Robins-egg blue-green, waxy.", emoji: "🩵",
  },
  {
    id: "rutile", name: "Rutile", group: "mineral", mohs: 6.5,
    luster: ["metallic", "adamantine"], colors: ["brown", "red", "black"],
    habit: ["crystals"], streak: "brown", gravity: "medium",
    looks: "Slender red-brown metallic needle crystals.",
    hints: "Shiny needles; often inside quartz (rutilated).", emoji: "🪡",
  },
  {
    id: "zeolite", name: "Zeolite", group: "mineral", mohs: 5,
    luster: ["vitreous"], colors: ["white", "clear"],
    habit: ["crystals"], streak: "white", gravity: "light",
    looks: "White needle clusters in cavities of volcanic rock.",
    hints: "Delicate white needles in bubbles of basalt.", emoji: "❄️",
  },
  {
    id: "malachite_chrysocolla", name: "Chrysocolla", group: "mineral", mohs: 3,
    luster: ["waxy", "earthy"], colors: ["blue", "green"],
    habit: ["massive"], streak: "light blue", gravity: "light",
    looks: "Bright turquoise-blue waxy crusts.",
    hints: "Blue-green, lightweight, often in copper zones.", emoji: "🩵",
  },
];

export const ROCK_COUNT = ROCKS.length;

export function findSpec(id?: string): RockSpec | undefined {
  if (!id) return undefined;
  return ROCKS.find((r) => r.id === id);
}

/** Group label with count, for the guide */
export function groupedRocks(): { group: RockGroup; label: string; rocks: RockSpec[] }[] {
  const order: RockGroup[] = ["igneous", "sedimentary", "metamorphic", "mineral"];
  return order.map((g) => ({
    group: g,
    label:
      g === "igneous"
        ? "Igneous — from cooled magma & lava"
        : g === "sedimentary"
          ? "Sedimentary — from layers & deposits"
          : g === "metamorphic"
            ? "Metamorphic — changed by heat & pressure"
            : "Minerals — single crystals & specimens",
    rocks: ROCKS.filter((r) => r.group === g),
  }));
}
